image: node:16.14.2

cache:
  paths:
    - node_modules/

before_script:
  - npm install hexo-cli -g
  - test -e package.json && npm install

pages:
  script:
    - hexo clean
    - hexo generate
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
