# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Sidney DING
subtitle: Keep quiet time for time
description: You laugh at me for being different, but I laugh at you for being the same.
keywords: Sidney, Ding, Sidney Ding, SidneyGod
author: Sidney Ding
language: en
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://sidneyding.cn/
root: /
permalink: posts/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - LICENSE
  - CNAME
  - js/**/*
  - css/**/*
  - images/**/*
  - fonts/**/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: false
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# https://github.com/amlove2/hexo-generator-topindex
topindex_generator:
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:SidneyGod/SidneyGod.github.io.git
  branch: blog-hexo

# Extensions
## Plugins: https://hexo.io/plugins/ npm install hexo-generator-feed --save
### hexo-generator-sitemap・SEO 核心
sitemap:
  path: sitemap.xml
  limit: 9999

### Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20
  order_by: -date
  icon: icon.png
  autodiscovery: true

### Local Search
search:
  path: search.xml
  field: post
  format: html
  content: true
  limit: 999

### https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false

### https://github.com/Rozbo/hexo-abbrlink
abbrlink:
  alg: crc32  # support crc16(default) and crc32
  rep: hex    # support dec(default) and hex
  drafts: false   # (true)Process draft,(false)Do not process draft. false(default) 
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true  # true(default)
     depth:        # 3(default)
     over_write: false 
  auto_title: false # enable auto title, it can auto fill the title by path
  auto_date: false # enable auto date, it can auto fill the date by time today
  force: false

### https://github.com/chenzhutian/hexo-all-minifier
all_minifier: true
html_minifier:
  enable: true
  ignore_error: false
  silent: true
  exclude:
  collapseBooleanAttributes: true
  collapseWhitespace: true
  # Ignore '<!-- more -->' https://hexo.io/docs/tag-plugins#Post-Excerpt
  ignoreCustomComments: [ !!js/regexp /^\s*more/]
  removeComments: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  minifyJS: true
  minifyCSS: true
js_minifier:
  enable: true
  mangle: true
  silent: true
  output:
  compress:
  exclude: 
    - '*.min.js'
css_minifier:
  enable: true
  silent: true
  exclude: 
    - '*.min.css'
image_minifier:
  enable: true
  interlaced: false  # Optimize svg multiple times until it’s fully optimized. Defaults to false.
  multipass: false
  optimizationLevel: 4  # 0-7
  pngquant: false
  progressive: false
  silent: true

### https://github.com/next-theme/hexo-optimize
filter_optimize:
  enable: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: true
  css:
    # minify all css files
    minify: true
    # bundle loaded css files into one
    bundle: false
    # use a script block to load css elements dynamically
    delivery: []
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines: []
    excludes: []
  js:
    # minify all js files
    minify: true
    # bundle loaded js files into one
    bundle: false
    excludes: []
  # set the priority of this plugin,
  # lower means it will be executed first, default of Hexo is 10
  priority: 12

### https://github.com/hexojs/hexo-renderer-markdown-it
markdown:
  # 默认"commonmark": 使用严格 CommandMark 规定
  # "default": 默认配置, 类似于 GFM
  # "zero": 禁用所有预设
  preset: "default"
  render:
    # 是否解析 HTML 内容, 如果为 true 则表示解析, false 表示将 HTML 转意为文本
    html: true
    # 将 HTML 内容渲染为 XHTML 的形式(XHTML语法非常严格, 比如 <br> 标签必须要 <br/> 进行"自闭和"
    xhtmlOut: false
    langPrefix: 'language-'
    # true 则将所有换行渲染为 <br> 标签 # 这种行为不属于 CommandMark 和 GFM
    breaks: false
    # true 则自动解析链接并添加为 <a> 标签, false 则将链接渲染为文本
    linkify: false
    # 默认 true，自动转义各种排版用字符, 如 ©
    typographer: false
    # 当 typographer 为 true 时的自动转换引号的行为，表示将 "1" '2' 转换为 “1” ‘2’
    quotes: '“”‘’'
  # preset 定义时的渲染规则
  # "zero" 表示禁用所有规则而能单独启用规则
  # "default" 表示启用所有规则, 所以只能禁用特定规则
  # "commandmark" 将严格遵循 CommandMark 因此不能额外定义规则的启闭
  enable_rules:
  disable_rules:
    #- 'link'
    #- 'image'
  # 锚点的配置
  anchors:
    # 开始创建锚点的等级，如 "2" 则表示从 H2 开始创建一直到 H6(最后)
    level: 1
    # 如果遇到重复的锚点 ID 为其添加数字编号时在这个数字前添加的前缀
    collisionSuffix: ''
    # 以下为标题锚点配置
    permalink: true # 如果为 true 则创建一个除标题外带有固定地址的的锚点标签
    permalinkClass: 'header-anchor' # 定义固定锚点的 class 名
    permalinkSide: 'left' # 设定为 right 则会在标题后添加固定链接
    permalinkSymbol: '¶' # 定义固定链接使用的符号
    # 标题固定锚点到此结束
    case: 0 # 转换锚点 ID 中的字母为大写或小写，"0" 不转换；"1" 为小写；"2" 为大写
    separator: '-' # 用于替换空格的符号，默认为 "-"
  plugins:
    - markdown-it-abbr # https://github.com/markdown-it/markdown-it-abbr
    - markdown-it-image-lazy-loading
    # 解析 **。** 有点问题
    #- markdown-it-cjk-breaks # https://github.com/markdown-it/markdown-it-cjk-breaks
    - markdown-it-container # https://github.com/markdown-it/markdown-it-container
    - markdown-it-deflist # https://github.com/markdown-it/markdown-it-deflist
    - markdown-it-emoji # https://github.com/markdown-it/markdown-it-emoji
    - markdown-it-footnote # https://github.com/markdown-it/markdown-it-footnote
    # ++test++，会转化为下划线
    #- markdown-it-ins # https://github.com/markdown-it/markdown-it-ins
    - markdown-it-mark # https://github.com/markdown-it/markdown-it-mark
    - markdown-it-sub # https://github.com/markdown-it/markdown-it-sub
    - markdown-it-sup # https://github.com/markdown-it/markdown-it-sup
    - name: '@renbaoshuo/markdown-it-katex'  # https://github.com/renbaoshuo/markdown-it-katex
      options:
        #skipDelimitersCheck: true
        strict: false   # 关闭strict模式，不再输出该类warn
        #throwOnError: false
    #- markdown-it-task-lists # https://github.com/revin/markdown-it-task-lists
